### ISSUE TITLE
branch-status vs atom-branch-status for package name?

### ISSUE THREAD

**Issue by bruce** [nakajima/atom-branch-status#2]
Hi Pat!

Love, love, love this.

I've been thinking about Atom package naming a bit; considering Atom packages are "private" packages (so presumably there's no name collision with npm?), and it probably doesn't make sense to have people `apm install atom-foo` vs `apm install foo`, what do you think about having repos named `atom-foo`, but just naming the packages `foo`?

I struggled with this choice in my first package, [csscomb](https://github.com/bruce/atom-csscomb).

**Comment by maddox** [comment]
This was done even more to the maxx with #10.

Closing this.
