### ISSUE TITLE
CTRL+S prevents me from saving edited document

### ISSUE THREAD

**Issue by vBm** [nakajima/atom-branch-status#5]
Due to having the same key as regular save file, so when hitting the `ctrl+s` file is not saved.
Using latest stable (0.99.0-ea0773e) build available from [someguy123](http://atom.someguy123.com/)'s page.

**Comment by kankaristo** [comment]
@maddox, this was also fixed in #10 (the polling is automatic, so the key binding was removed).

**Comment by maddox** [comment]
Ah ok.
