### ISSUE TITLE
Issue during installation

### ISSUE THREAD

**Issue by morkot** [nakajima/atom-branch-status#9]
Hi guys,

On win 8.1 has the issue: `gypnpm ERR! keytar@1.0.1 install: node-gyp rebuild`

\> keytar@1.0.1 install C:\Users\ANDRII~1\AppData\Local\Temp\apm-install-dir-114719-1180-17d38ia\node_modules\branch-status\node_modules\keytar
\> node-gyp rebuild

C:\Users\ANDRII~1\AppData\Local\Temp\apm-install-dir-114719-1180-17d38ia\node_modules\branch-status\node_modules\keytar>node "c:\ProgramData\chocolatey\lib\Atom.0.123.0\tools\Atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

npm http GET https://registry.npmjs.org/request/2.33.0
npm http GET https://registry.npmjs.org/keytar
npm http 304 https://registry.npmjs.org/keytar
npm http 304 https://registry.npmjs.org/request/2.33.0
npm http GET https://registry.npmjs.org/nan/0.8.0
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/aws-sign2
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/assert-plus/0.1.2
npm http GET https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/ctype/0.5.2
npm http GET https://registry.npmjs.org/punycode
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/ctype/0.5.2
npm http 304 https://registry.npmjs.org/punycode
npm http 304 https://registry.npmjs.org/assert-plus/0.1.2
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/asn1/0.1.11
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/nan/0.8.0
gypnpm ERR! keytar@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@1.0.1 install script.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\ProgramData\\chocolatey\\lib\\Atom.0.123.0\\tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\ProgramData\\chocolatey\\lib\\Atom.0.123.0\\tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\ProgramData\\chocolatey\\lib\\Atom.0.123.0\\tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Andrii_Melekhovskiy\\.atom\\.apmrc" "install" "C:\\Users\\Andrii_Melekhovskiy\\.atom\\.node-gyp\\.atom\\.apm\\branch-status\\0.7.0\\package.tgz" "--target=0.11.13" "--arch=ia32"
npm ERR! cwd C:\Users\ANDRII~1\AppData\Local\Temp\apm-install-dir-114719-1180-17d38ia
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE

**Comment by kankaristo** [comment]
Any news on this? Install also fails for me on Ubuntu 14.04.2 LTS.

**Comment by kankaristo** [comment]
This could just be down to the `keytar` version? When I changed the version in `package.json` like this:
```
  "dependencies": {
    "request": "2.33.0",
    "keytar": "^2"
  }
```

It seems to install fine, it creates a menu item under "Packages" (but not the command palette?), but it doesn't seem to do anything... I've tried it with a few different repositories and branches (including https://github.com/atom/atom), but the branch name in the status bar doesn't change color.

**Comment by kankaristo** [comment]
Okay, I fixed a bunch of deprecations and temporarily disabled using the GitHub token (`getToken()` was returning `null`), so I can test it with public repositories.

The branch name is now turning green, but it seems to always turn green, no matter what the actual status is.

**Comment by kankaristo** [comment]
I switched this to using a personal access token (OAuth) given by the user in the package's settings. This is probably better anyway, because it will be used only for this package.

This seems to be working perfectly now. The `keytar` dependency is no longer needed, and a personal access token in the package's settings seems to be norm with Atom packages (I'm looking at `sync-settings` and `gist-it`, I'm not aware of any others that need a token).

@nakajima, the package seems to be unmaintained, but would you accept a pull request for fixing this? I also fixed half a dozen deprecations and removed the `Ctrl-S` key binding which is no longer needed (and conflicts with "Save file").

**Comment by nakajima** [comment]
@kankaristo I'm always happy to accept PRs.

**Comment by kankaristo** [comment]
Okay, I'll clean up my code a bit and send one later this week (probably tomorrow). :)
